classdef Text
    properties (Access = public)
        easy = struct;
        medium = struct;
        hard = struct;
        impossible = struct;
    end

    methods (Access = public)
        % https://www.mathworks.com/matlabcentral/answers/308778-randomly-scramble-letters-in-a-single-word
        function term = scramble(~, term)
            y = char(size(term));

            for k = 1:length(term)
                [y(k), index] = datasample(term, 1, 'Replace', false);
                term(index) = [];
            end

            term = y;
        end

        function text = Text()
            % Easy
            text.easy.a = {
                {'Synapse', 'Synapse'}, ...
                {'Serotonin', 'Serotonin'}, ...
                {'Neuron', 'Neuron'}, ...
                {'Oligodendrocytes', 'Oligodendrocytes'}, ...
                {'Cerebellum', 'Cerebellum'}, ...
                {'Myelin', 'Myelin'}, ...
                {'Hippocampus', 'Hippocampus'}, ...
                {'Amygdala', 'Amygdala'}, ...
                {'Axon', 'Axon'}, ...
                {'Dopamine', 'Dopamine'}, ...
                {'Glia', 'Glia'}, ...
                {'Cognition', 'Cognition'} ...
            };

            text.easy.b = {
                {'Action Potential', 'Action Potential'}, ...
                {'Amino Acid', 'Amino Acid'}, ...
                {'Brain Waves', 'Brain Waves'}, ...
                {'Broca''s Area', 'Broca''s Area'}, ...
                {'Cell Body', 'Cell Body'}, ...
                {'Cerebrum', 'Cerebrum'}, ...
                {'Chromosome', 'Chromosome'}, ...
                {'Cochlea', 'Cochlea'}, ...
                {'Dendrites', 'Dendrites'}, ...
                {'Endorphins', 'Endorphins'}, ...
                {'Fissure', 'Fissure'}, ...
                {'Gyri', 'Gyri'} ...
            };

            % Medium
            text.medium.a = {
                {'Acetylcholine', 'Acetylcholine'}, ...
                {'Achromatopsia', 'Achromatopsia'}, ...
                {'Action Potential', 'Action Potential'}, ...
                {'Activation', 'Activation'}, ...
                {'Adaptation ', 'Adaptation'}, ...
                {'Adenylyl Cyclase', 'Adenylyl Cyclase'}, ...
                {'Adhesion Molecules', 'Adhesion Molecules'}, ...
                {'Adrenaline', 'Adrenaline'}, ...
                {'Adrenal Medulla', 'Adrenal Medulla'}, ...
                {'Adrenergic', 'Adrenergic'}, ...
                {'Afferent', 'Afferent'}, ...
                {'Agnosia', 'Agnosia'} ...
            };

            text.medium.b = {
                {'Nerve Cell', 'Nerve Cell'}, ...
                {'Nerve Impulse', 'Nerve Impulse'}, ...
                {'Nervous System', 'Nervous System'}, ...
                {'Neural Induction', 'Neural Induction'}, ...
                {'Neurogenesis ', 'Neurogenesis'}, ...
                {'Neuroplasticity', 'Neuroplasticity'}, ...
                {'Neuron', 'Neuron'}, ...
                {'Neuroscience', 'Neuroscience'}, ...
                {'Neurotransmitter', 'Neurotransmitter'}, ...
                {'Neurotrophic Factor', 'Neurotrophic Factor'}, ...
                {'Nucleotide', 'Nucleotide'}, ...
                {'Neuroimaging', 'Neuroimaging'} ...
            };

            % Hard
            text.hard.a = {
                {'Prosencephalon', 'Prosencephalon'}, ...
                {'Mesencephalon', 'Mesencephalon'}, ...
                {'Rhombencephalon', 'Rhombencephalon'}, ...
                {'Oligodendrocytes', 'Oligodendrocytes'}, ...
                {'Electroencephalography ', 'Electroencephalography'}, ...
                {'Mesolimbic Pathway', 'Mesolimbic Pathway'}, ...
                {'Diencephalon', 'Diencephalon'}, ...
                {'Inferior Colliculi', 'Inferior Colliculi'}, ...
                {'Innervation', 'Innervation'}, ...
                {'Medial Lemniscus', 'Medial Lemniscus'}, ...
                {'Nociceptors', 'Nociceptors'}, ...
                {'Norepinephrine', 'Norepinephrine'} ...
            };

            text.hard.b = {
                {'Prosencephalon', reverse('Prosencephalon')}, ...
                {'Mesencephalon', reverse('Mesencephalon')}, ...
                {'Rhombencephalon', reverse('Rhombencephalon')}, ...
                {'Oligodendrocytes', reverse('Oligodendrocytes')}, ...
                {'Electroencephalography ', reverse('Electroencephalography')}, ...
                {'Mesolimbic Pathway', reverse('Mesolimbic Pathway')}, ...
                {'Diencephalon', reverse('Diencephalon')}, ...
                {'Inferior Colliculi', reverse('Inferior Colliculi')}, ...
                {'Innervation', reverse('Innervation')}, ...
                {'Medial Lemniscus', reverse('Medial Lemniscus')}, ...
                {'Nociceptors', reverse('Nociceptors')}, ...
                {'Norepinephrine', reverse('Norepinephrine')} ...
            };

            % Impossible
            text.impossible.a = {
                {'Synapse', text.scramble('Synapse')}, ...
                {'Serotonin', text.scramble('Serotonin')}, ...
                {'Neuron', text.scramble('Neuron')}, ...
                {'Oligodendrocytes', text.scramble('Oligodendrocytes')}, ...
                {'Cerebellum', text.scramble('Cerebellum')}, ...
                {'Myelin', text.scramble('Myelin')}, ...
                {'Hippocampus', text.scramble('Hippocampus')}, ...
                {'Amygdala', text.scramble('Amygdala')}, ...
                {'Axon', text.scramble('Axon')}, ...
                {'Dopamine', text.scramble('Dopamine')}, ...
                {'Glia', text.scramble('Glia')}, ...
                {'Cognition', text.scramble('Cognition')} ...
            };

            text.impossible.b = {
                {'Action Potential', text.scramble('Action Potential')}, ...
                {'Amino Acid', text.scramble('Amino Acid')}, ...
                {'Brain Waves', text.scramble('Brain Waves')}, ...
                {'Broca''s Area', text.scramble('Broca''s Area')}, ...
                {'Cell Body', text.scramble('Cell Body')}, ...
                {'Cerebrum', text.scramble('Cerebrum')}, ...
                {'Chromosome', text.scramble('Chromosome')}, ...
                {'Cochlea', text.scramble('Cochlea')}, ...
                {'Dendrites', text.scramble('Dendrites')}, ...
                {'Endorphins', text.scramble('Endorphins')}, ...
                {'Fissure', text.scramble('Fissure')}, ...
                {'Gyri', text.scramble('Gyri')} ...
            };

            text.impossible.c = {
                {'Acetylcholine', text.scramble('Acetylcholine')}, ...
                {'Achromatopsia', text.scramble('Achromatopsia')}, ...
                {'Action Potential', text.scramble('Action Potential')}, ...
                {'Activation', text.scramble('Activation')}, ...
                {'Adaptation ', text.scramble('Adaptation')}, ...
                {'Adenylyl Cyclase', text.scramble('Adenylyl Cyclase')}, ...
                {'Adhesion Molecules', text.scramble('Adhesion Molecules')}, ...
                {'Adrenaline', text.scramble('Adrenaline')}, ...
                {'Adrenal Medulla', text.scramble('Adrenal Medulla')}, ...
                {'Adrenergic', text.scramble('Adrenergic')}, ...
                {'Afferent', text.scramble('Afferent')}, ...
                {'Agnosia', text.scramble('Agnosia')} ...
            };

            text.impossible.d = {
                {'Nerve Cell', text.scramble('Nerve Cell')}, ...
                {'Nerve Impulse', text.scramble('Nerve Impulse')}, ...
                {'Nervous System', text.scramble('Nervous System')}, ...
                {'Neural Induction', text.scramble('Neural Induction')}, ...
                {'Neurogenesis ', text.scramble('Neurogenesis')}, ...
                {'Neuroplasticity', text.scramble('Neuroplasticity')}, ...
                {'Neuron', text.scramble('Neuron')}, ...
                {'Neuroscience', text.scramble('Neuroscience')}, ...
                {'Neurotransmitter', text.scramble('Neurotransmitter')}, ...
                {'Neurotrophic Factor', text.scramble('Neurotrophic Factor')}, ...
                {'Nucleotide', text.scramble('Nucleotide')}, ...
                {'Neuroimaging', text.scramble('Neuroimaging')} ...
            };


            text.impossible.e = {
                {'Prosencephalon', text.scramble('Prosencephalon')}, ...
                {'Mesencephalon', text.scramble('Mesencephalon')}, ...
                {'Rhombencephalon', text.scramble('Rhombencephalon')}, ...
                {'Oligodendrocytes', text.scramble('Oligodendrocytes')}, ...
                {'Electroencephalography ', text.scramble('Electroencephalography')}, ...
                {'Mesolimbic Pathway', text.scramble('Mesolimbic Pathway')}, ...
                {'Diencephalon', text.scramble('Diencephalon')}, ...
                {'Inferior Colliculi', text.scramble('Inferior Colliculi')}, ...
                {'Innervation', text.scramble('Innervation')}, ...
                {'Medial Lemniscus', text.scramble('Medial Lemniscus')}, ...
                {'Nociceptors', text.scramble('Nociceptors')}, ...
                {'Norepinephrine', text.scramble('Norepinephrine')} ...
            };

            text.impossible.f = {
                {'Prosencephalon', text.scramble('Prosencephalon')}, ...
                {'Mesencephalon', text.scramble('Mesencephalon')}, ...
                {'Rhombencephalon', text.scramble('Rhombencephalon')}, ...
                {'Oligodendrocytes', text.scramble('Oligodendrocytes')}, ...
                {'Electroencephalography ', text.scramble('Electroencephalography')}, ...
                {'Mesolimbic Pathway', text.scramble('Mesolimbic Pathway')}, ...
                {'Diencephalon', text.scramble('Diencephalon')}, ...
                {'Inferior Colliculi', text.scramble('Inferior Colliculi')}, ...
                {'Innervation', text.scramble('Innervation')}, ...
                {'Medial Lemniscus', text.scramble('Medial Lemniscus')}, ...
                {'Nociceptors', text.scramble('Nociceptors')}, ...
                {'Norepinephrine', text.scramble('Norepinephrine')} ...
            };
        end

        function field = select(~, s)
            fields = fieldnames(s);
            first = fields(1);
            last = fields(end);
            index = char(first):char(last);
            field = index(randi(length(index)));
        end

        function element = get(text, difficulty)
            switch difficulty
                case 'easy'
                    field = text.select(text.easy);
                    element = text.easy.(field);
                case 'medium'
                    field = text.select(text.medium);
                    element = text.medium.(field);
                case 'hard'
                    field = text.select(text.hard);
                    element = text.hard.(field);
                otherwise
                    field = text.select(text.impossible);
                    element = text.impossible.(field);
            end
        end
    end
end